import { readFileSync, existsSync } from 'node:fs';
import { expected } from './seo-expectations.mjs';
export const site = JSON.parse(readFileSync('content/generated/site.json', 'utf8'));
export const home = JSON.parse(readFileSync('content/generated/home.json', 'utf8'));
export const pages = JSON.parse(readFileSync('content/generated/pages.json', 'utf8'));
export const forbidden = /starter|placeholder|skeleton|example\.github\.io|yorich|fact pack|evidence id|generated by|ai generated|codex|claude|chatgpt|localhost|127\.0\.0\.1|\/Users\/|sportskeeda|Wood Farm|Mushroom Farm|Chemical Factory|warrior legions|gunner legions|flood mission/i;
export function check(condition, message) { if (!condition) throw new Error(message); }
const all = [home, ...pages];
check(typeof site.readyForLaunch === 'boolean', 'Launch status must be a boolean');
check(site.readyForLaunch || process.argv.includes('--prelaunch'), 'Launch status is disabled; use --prelaunch only while preparing content.');
check(site.hosting.siteUrl === 'https://build-an-ant-empire.github.io' && site.hosting.basePath === '' && site.hosting.customDomain === null, 'Incorrect production hosting');
check(site.repositoryUrl === null, 'Repository URL must remain private');
check(site.game.officialUrl === 'https://www.roblox.com/games/78490532994307/Build-An-Ant-Empire', 'Incorrect official game URL');
check(all.length === 11 && new Set(all.map(p => p.slug)).size === 11, 'Exactly eleven unique core routes required');
const titles = new Set(), descriptions = new Set();
function validateTable(table) {
  if (!table) return;
  check(table.caption && table.columns?.length && table.rows?.length, 'Table requires caption, columns and rows');
  for (const row of table.rows) check(row.length === table.columns.length && row.every(cell => typeof cell === 'string' && cell.length), 'Invalid table row');
}
for (const page of all) {
  const target = expected[page.slug];
  check(target && page.enabled && page.navVisible, `Missing or disabled route ${page.slug}`);
  check(page.title === target.title && page.description === target.description && page.hero.heading === target.h1, `Metadata differs from required copy: ${page.slug}`);
  check(page.title.length <= 60 && page.description.length <= 160, `Metadata too long: ${page.slug}`);
  check(!titles.has(page.title) && !descriptions.has(page.description), 'Duplicate metadata');
  titles.add(page.title); descriptions.add(page.description);
  check(!forbidden.test(JSON.stringify(page)), `Public copy contains prohibited text: ${page.slug}`);
  check(page.sections?.length && page.faq?.length && /^\d{4}-\d{2}-\d{2}$/.test(page.lastReviewed), `Incomplete content: ${page.slug}`);
  const ids = new Set();
  for (const section of page.sections) {
    check(section.id && section.heading && !ids.has(section.id), `Invalid/duplicate section anchor: ${page.slug}`); ids.add(section.id);
    validateTable(section.table);
    for (const sub of section.subsections ?? []) { check(sub.heading && Array.isArray(sub.paragraphs), 'Invalid subsection'); validateTable(sub.table); }
    for (const step of section.steps ?? []) check(step.heading && step.description, 'Incomplete step');
    for (const link of section.links ?? []) check(expected[link.slug], `Broken contextual link: ${link.slug}`);
  }
  for (const slug of page.relatedSlugs ?? []) check(expected[slug] && slug !== page.slug, `Broken related route: ${slug}`);
  for (const item of page.faq) check(item.question && item.answer, 'Empty FAQ item');
  for (const source of page.sourceLinks ?? []) check(site.allowedExternalDomains.includes(new URL(source.url).hostname), `Disallowed source: ${source.url}`);
}
for (const path of Object.values(site.assets)) check(existsSync(`public${path}`), `Missing asset: ${path}`);
check(!forbidden.test(JSON.stringify(site)), 'Invalid public site configuration');
console.log(`Content validation passed: ${all.length} pages. Launch status: ${site.readyForLaunch ? 'enabled' : 'disabled during preparation'}.`);
